tuto/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path("contact/",views.contact,name="contact"),
    path("booking/",views.booking,name="booking"),
    path("doctors/",views.doctors,name="doctors"),
    path("department/",views.department,name="department"),
    path('signup/',views.signup,name='signup'),
    path('user_login/',views.user_login,name='user_login'),
]

tuto/tuto/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from home import views


urlpatterns = [
    path('',views.index,name='index'),
    path("admin/", admin.site.urls),
    path("",include("home.urls")),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

tuto/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Departments(models.Model):
    dep_name = models.CharField(max_length=100)
    dep_description = models.TextField()

    def __str__(self):
        return self.dep_name

class Doctors(models.Model):
    doc_name = models.CharField(max_length=255)
    doc_spec = models.CharField(max_length=255)
    dep_name = models.ForeignKey(Departments, on_delete=models.CASCADE)
    doc_image = models.ImageField(upload_to="doctors")

    def __str__(self):
        return 'Dr. ' + self.doc_name + ' -(' + self.doc_spec + ')'

class Booking(models.Model):
    p_name = models.CharField(max_length=255)
    p_phone = models.CharField(max_length=10)
    p_email = models.EmailField()
    doc_name = models.ForeignKey(Doctors, on_delete=models.CASCADE)
    booking_date = models.DateField()
    booked_on = models.DateField(auto_now=True)


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, default=None,null=True,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

tuto/home/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Booking,UserProfileInfo

class DateInput(forms.DateInput):
    input_type = 'date'

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = '__all__'

        widgets = {
            'booking_date' : DateInput
        }

        labels = {
            'p_name' : 'Patient Name',
            'p_phone' : 'Phone number',
            'p_email' : 'E-mail id',
            'doc_name' : 'Doctors Name',
            'booking_date' : 'Booking date'
        }


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

tuto/home/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from .models import Departments,Doctors
from .forms import BookingForm,UserForm,UserProfileInfoForm
# Create your views here.
def index(request):
    return render(request,"index.html")

def contact(request):
    return render(request,"contact.html")

def booking(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,'confirmation.html')
    form = BookingForm()
    dict_form = {
        'form':form
    }
    return render(request,"booking.html",dict_form)

def doctors(request):
    dict_docs = {
        "doctors" : Doctors.objects.all()
    }
    return render(request,"doctors.html",dict_docs)

def department(request):
    dict_dept = {
        "dept":Departments.objects.all()
    }
    return render(request,"department.html",dict_dept)


@login_required
def special(request):
    return HttpResponse('You are logged in , Nice !')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def signup(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'signup.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")
        else:
            print("Someone tried to login and failed !")
            print("Username : {} and Password : {}".format(username,password))
            return HttpResponse('Invalid login details supplied')
    else:
        return render(request,'login.html')

tuto/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet"
    href="{% static '/css/style.css' %}">

  </head>

  <body>

    <nav class="navbar bg-primary navbar-expand-md">
      <div class="container">
        <div class="col-2 text-left pl-md-0">
          <h3 class="text-white"> City Hospital </h3>
        </div>
        
        <div
          class="collapse navbar-collapse justify-content-center col-md-8 navbar-collapse-3">
          <ul class="navbar-nav justify-content-center  fw-bold">
            <li class="nav-item active">
              <a class="nav-link text-white" href="{% url 'index' %}">Home </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'home:booking' %}">Booking</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'home:doctors' %}">Doctors</a>
            </li>
		        <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'home:department' %}">Departments</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'home:contact' %}">Contact Us</a>
            </li>
            <li class="nav-item ms-5">
              <a class="nav-link "  href="{% url 'home:signup' %}" style="color: yellow;">Sign Up</a>
            </li>
            <li class="nav-item"></li>
            {% if user.is_authenticated %}
                  <a class="nav-link" href="{% url 'logout' %}" style="color: red;">Logout</a>
            {% else %}
                  <a class="nav-link" href="{% url 'home:user_login' %}" style="color: green;">Login</a>
            {% endif %}
            </li>
          </ul>
        </div>
        
      </div>
    </nav>

    {% block content %}{% endblock %}






    
	
	
    <section class="">
      <footer class="pt-2 pb-2  bg-primary text-light">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12 col-md-8">
              <h4>Emergency Contact Number: 0123456789</h4>
            </div>
            <div class="col-12 col-md-4 mt-4 mt-md-0 text-center text-md-end">
              © 2022 City Hospital. All Rights Reserved
            </div>
          </div>
        </div>
      </footer>
    </section>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

  </body>

</html>

tuto/templates/booking.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
booking
{% endblock %}

{% block content %}

<h1 class="text-center">Make An appoinment</h1>
<hr>
<div class="container w-25 text-center p-3 my-5 bg-info">
    <form action="" method='POST'>
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary mb-4" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

tuto/templates/confirmation.html
{% extends "base.html" %}
{% block title %}
Booking Confirmation
{% endblock %}

{% block content %}
<div class="container text-center">
    <h1>Booking Confirmation</h1>

    <div class="alert alert-info" role="alert">
        We have received your appointment request , Our representative will reach you soon 
    </div>
</div>
{% endblock %}

tuto/templates/contact.html
{% extends "base.html" %}
{% block title %}
contact
{% endblock %}

{% block content %}
<h1>Contact page</h1>
{% endblock %}

tuto/templates/department.html
{% extends "base.html" %}
{% block title %}
departement
{% endblock %}

{% block content %}
<h1 class="text-center">Our Departements</h1>
<hr>

{% for d in dept %}
<div class="mx-auto w-50 bg-success text-center text-white p-3 my-5 border border-warning rounded">
    <h1>{{d.dep_name}}</h1>
    <p class="text-dark">{{d.dep_description}}</p>
</div>
{% endfor %}
{% endblock %}

tuto/templates/doctors.html
{% extends "base.html" %}
{% block title %}
doctors
{% endblock %}

{% block content %}
<h1 class="text-center">Our Doctors</h1>
<hr>
<div class="container text-center bg-dark">

    {% for d in doctors%}

    <div class="card text-center mx-3 my-3" style="width: 18rem;display: inline-block;">
        <img src="{{d.doc_image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Dr. {{d.doc_name}}</h5>
          <p class="card-text">{{d.doc_spec}}</p>
          <h6>{{d.dep_name}} Department</h6>
        </div>
    </div>

    {% endfor %}

</div>
{% endblock %}

tuto/templates/index.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock %}

{% block content %}

{% load static %}

<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="{% static '/images/car1.jpg' %}" class="d-block w-100" alt="...">
        <
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="{% static '/images/car2.jpg' %}" class="d-block w-100" alt="...">
        
      </div>
      <div class="carousel-item">
        <img src="{% static '/images/car3.jpg' %}" class="d-block w-100" alt="...">
        
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


{% endblock %}

tuto/templates/login.html
{% extends "base.html" %}
{% block title %}
Login
{% endblock %}

{% block content %}

{% load static %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="POST" action="{% url 'home:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

tuto/templates/signup.html
{% extends "base.html" %}
{% block title %}
Signup
{% endblock %}

{% block content %}

{% load static %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}